name: Setup CI Helpers
description: Make ci-helpers.sh available and source it for subsequent bash steps.
outputs:
  helpers_path:
    description: Absolute path to ci-helpers.sh
    value: ${{ steps.expose.outputs.path }}
runs:
  using: composite
  steps:
    - id: expose
      shell: bash
      run: |
        set -Eeuo pipefail

        # Locate helpers
        CAND=(
          "$GITHUB_ACTION_PATH/../../ci/ci-helpers.sh"
          "$GITHUB_ACTION_PATH/../../ci/ci-helper.sh"
        )
        HELPERS=""
        for p in "${CAND[@]}"; do
          [[ -f "$p" ]] && HELPERS="$p" && break
        done
        if [[ -z "$HELPERS" ]]; then
          echo "ci helpers not found (looked for ci-helpers.sh/ci-helper.sh)" >&2
          exit 1
        fi

        # Ensure BASH_ENV exists even under `set -u`
        : "${BASH_ENV:=$RUNNER_TEMP/bash_env}"
        touch "$BASH_ENV"

        # Expose path as output
        echo "path=$HELPERS" >> "$GITHUB_OUTPUT"

        # Auto-source for subsequent bash steps
        {
          echo "# Added by ci-helpers setup"
          echo "source \"$HELPERS\""
        } >> "$BASH_ENV"

        # Convenience env var
        echo "CI_HELPERS_SH=$HELPERS" >> "$GITHUB_ENV"

        echo "ci-helpers ready at $HELPERS"
