name: Lint (shellcheck)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint helper library
        run: |
          set -e
          if [ -f ci/ci-helpers.sh ]; then
            shellcheck ci/ci-helpers.sh
          fi
          if [ -f ci/ci-helper.sh ]; then
            shellcheck ci/ci-helper.sh
          fi
